[tool.poetry]
name = "accounting-app"
version = "0.1.0"
description = ""
authors = ["Zack Plauché"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.6.2"
streamlit = "^1.31.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
